version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1
workflows:
  build:
    jobs:
      - cypress/run # "run" job comes from "cypress" orb hi pretending to change a thing
          record: true
          parallel: true
          parallelism: 4
