version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  version: 2.1
  build:
    jobs:
      - cypress/run:
          record: true
          store_artifacts: true
          parallel: true
          parallelism: 4
